# main.py
"""
End-to-End Loan Processing Demo – Retail + SME (Combined)
=========================================================
Tabs: Applications (Retail + SME with search + side panel) | Results

Data is loaded from:
    retail_applicants.json   ← generated by synthetic_data_generator.py
    sme_applicants.json      ← generated by synthetic_data_generator.py

Run:
    flet run main.py

Package:
    flet pack main.py --name "LoanDemo-Final" --icon assets/bank.ico \
        --add-data "assets;assets" \
        --add-data "retail_applicants.json;." \
        --add-data "sme_applicants.json;." \
        --hidden-import matplotlib --hidden-import sarvamai --hidden-import numpy
"""

import json
import random
import time

import flet as ft

from retail_pipeline import RetailPipeline
from sme_pipeline import SMEPipeline
from sarvam_utils import stt_from_file, translate_to_hindi

# ── Lazy-import gauges (matplotlib not required at startup) ──────────────────
try:
    from gauges import dscr_gauge, ltv_gauge
    GAUGES_AVAILABLE = True
except ImportError:
    GAUGES_AVAILABLE = False

# ─────────────────────────────────────────────────────────────────────────────
# Load synthetic data
# ─────────────────────────────────────────────────────────────────────────────
try:
    with open("retail_applicants.json", "r", encoding="utf-8") as _f:
        RETAIL_SAMPLES: list = json.load(_f)
    print(f"✅  Loaded {len(RETAIL_SAMPLES):,} retail applicants")
except FileNotFoundError:
    RETAIL_SAMPLES = []
    print("⚠️  retail_applicants.json not found – run synthetic_data_generator.py first")

try:
    with open("sme_applicants.json", "r", encoding="utf-8") as _f:
        SME_SAMPLES: list = json.load(_f)
    print(f"✅  Loaded {len(SME_SAMPLES):,} SME applicants")
except FileNotFoundError:
    SME_SAMPLES = []
    print("⚠️  sme_applicants.json not found – run synthetic_data_generator.py first")

# ─────────────────────────────────────────────────────────────────────────────
# Pipelines (singleton)
# ─────────────────────────────────────────────────────────────────────────────
_retail_pipeline = RetailPipeline()
_sme_pipeline    = SMEPipeline()


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────
def fmt_inr(n) -> str:
    try:
        return f"₹{float(n):,.0f}"
    except Exception:
        return str(n)


def kv_row(label: str, value: str) -> ft.Row:
    return ft.Row([
        ft.Text(f"{label}:", weight="bold", size=13, width=220, color=ft.colors.BLUE_GREY_200),
        ft.Text(str(value), size=13, selectable=True, expand=True),
    ], spacing=8)


# ─────────────────────────────────────────────────────────────────────────────
# Main Flet app
# ─────────────────────────────────────────────────────────────────────────────
def main(page: ft.Page):
    page.title       = "Loan Processing Demo – Retail & SME"
    page.theme_mode  = ft.ThemeMode.DARK
    page.padding     = 0
    page.window_width  = 1400
    page.window_height = 860
    page.bgcolor     = "#0d1117"
    page.fonts       = {}

    # ── Shared state ────────────────────────────────────────────────────────
    picked_file   = [None]
    last_result   = [{}]
    active_mode   = ["retail"]   # "retail" | "sme"

    # ── File picker ─────────────────────────────────────────────────────────
    def on_file_picked(e: ft.FilePickerResultEvent):
        if e.files:
            picked_file[0] = e.files[0].path
            page.show_snack_bar(ft.SnackBar(ft.Text(f"Loaded: {e.files[0].name}")))

    file_picker = ft.FilePicker(on_result=on_file_picked)
    page.overlay.append(file_picker)

    # ── Results panel ───────────────────────────────────────────────────────
    results_col = ft.Column(scroll=ft.ScrollMode.AUTO, spacing=10, expand=True)

    def show_results(result: dict, mode: str):
        results_col.controls.clear()
        last_result[0] = result

        decision = result.get("decision", "N/A")
        color    = (
            ft.colors.GREEN_400  if "APPROVE" in str(decision) else
            ft.colors.ORANGE_400 if "REVIEW"  in str(decision) else
            ft.colors.RED_400
        )

        # Header chip
        results_col.controls.append(
            ft.Container(
                ft.Text(f"▶  {decision}", size=22, weight="bold", color=color),
                padding=ft.padding.symmetric(horizontal=20, vertical=12),
                bgcolor=ft.colors.with_opacity(0.18, color),
                border_radius=10,
            )
        )

        # Key metrics
        if mode == "retail":
            metrics = [
                ("Applicant",         result.get("full_name", result.get("name", "N/A"))),
                ("Loan Type",         result.get("loan_type", result.get("type", "N/A"))),
                ("City",              result.get("city", "N/A")),
                ("CIBIL Score",       result.get("cibil_score", result.get("cibil", "N/A"))),
                ("Monthly Income",    fmt_inr(result.get("net_monthly_income", result.get("monthly_income", 0)))),
                ("Proposed EMI",      fmt_inr(result.get("proposed_emi", 0))),
                ("FOIR Pre-Loan",     f"{result.get('foir_pre_loan', 0):.1f}%"),
                ("FOIR Post-Loan",    f"{result.get('foir_post_loan', 0):.1f}% (max {result.get('max_allowed_foir', 50)}%)"),
                ("FOIR Status",       result.get("foir_status", "N/A")),
                ("Loan Requested",    fmt_inr(result.get("loan_amount_requested", result.get("loan_amt", 0)))),
                ("Approved Amount",   fmt_inr(result.get("approved_amount", 0))),
                ("Interest Rate",     f"{result.get('interest_rate', 'N/A')}%"),
                ("Credit Score",      f"{result.get('final_score', 'N/A')} / 98"),
                ("Risk Grade",        result.get("bureau_risk_grade", "N/A")),
                ("LTV Ratio",         f"{result.get('ltv_ratio', 0):.1f}%"),
                ("NACH UMRN",         result.get("nach_umrn", "N/A")),
                ("Loan Account",      result.get("loan_account_number", "N/A")),
                ("Disbursement Mode", result.get("disbursement_mode", "N/A")),
            ]
        else:
            metrics = [
                ("Business",          result.get("name", result.get("business_name", "N/A"))),
                ("Loan Type",         result.get("loan_type", result.get("type", "N/A"))),
                ("City",              result.get("city", "N/A")),
                ("Industry",          result.get("industry", "N/A")),
                ("Annual Turnover",   fmt_inr(result.get("annual_turnover", result.get("turnover", 0)))),
                ("Promoter CIBIL",    result.get("promoter_cibil_score", result.get("cibil", "N/A"))),
                ("DSCR",              f"{result.get('dscr', 0):.2f}  (≥1.25 required)"),
                ("Current Ratio",     result.get("current_ratio", "N/A")),
                ("Debt / Equity",     result.get("debt_to_equity", "N/A")),
                ("Gross Margin",      f"{result.get('gross_profit_margin', 0):.1f}%"),
                ("Financial Health",  f"{result.get('financial_health_score', 0):.1f} / 98"),
                ("Collateral Value",  fmt_inr(result.get("collateral_value", 0))),
                ("LTV Ratio",         f"{result.get('ltv_ratio', 0):.1f}%"),
                ("Risk Score",        f"{result.get('total_score', 'N/A')} / 98"),
                ("Risk Grade",        result.get("risk_grade", "N/A")),
                ("Loan Requested",    fmt_inr(result.get("loan_amount_requested", result.get("loan_amt", 0)))),
                ("Sanctioned Amount", fmt_inr(result.get("sanctioned_amount", 0))),
                ("Interest Rate",     f"{result.get('final_interest_rate', 'N/A')}%"),
                ("NACH UMRN",         result.get("nach_umrn", "N/A")),
                ("Loan Account",      result.get("loan_account_number", "N/A")),
            ]

        for label, val in metrics:
            results_col.controls.append(kv_row(label, val))

        # Gauge
        if GAUGES_AVAILABLE:
            try:
                if mode == "sme":
                    dscr = result.get("dscr", 1.0) or 1.0
                    img  = dscr_gauge(float(dscr))
                    results_col.controls.append(
                        ft.Image(src_base64=img, width=340, height=200, fit=ft.ImageFit.CONTAIN)
                    )
                ltv = result.get("ltv_ratio", 0) or 0
                if ltv > 0:
                    img2 = ltv_gauge(float(ltv))
                    results_col.controls.append(
                        ft.Image(src_base64=img2, width=340, height=200, fit=ft.ImageFit.CONTAIN)
                    )
            except Exception as ge:
                results_col.controls.append(ft.Text(f"Gauge error: {ge}", color=ft.colors.ORANGE_300))

        # Stage log
        results_col.controls.append(ft.Divider(height=16))
        results_col.controls.append(ft.Text("Stage Log", weight="bold", size=15))
        for log in result.get("logs", []):
            results_col.controls.append(
                ft.Text(log, size=12, font_family="monospace", color=ft.colors.CYAN_200)
            )

        # Switch to results tab
        tabs_ctrl.selected_index = 1
        page.update()

    # ── Side panel ───────────────────────────────────────────────────────────
    side_panel_col = ft.Column(spacing=10, scroll=ft.ScrollMode.AUTO, expand=True)
    side_container = ft.Container(
        content=side_panel_col,
        bgcolor="#161b22",
        padding=16,
        border_radius=10,
        border=ft.border.all(1, "#30363d"),
        visible=False,
        width=340,
        expand=False,
    )

    def show_side_panel(app: dict, is_retail: bool):
        side_panel_col.controls.clear()

        if is_retail:
            title   = app.get("name", "N/A")
            details = [
                ("City",       app.get("city", "N/A")),
                ("Gender",     app.get("gender", "N/A")),
                ("Age",        app.get("age", "N/A")),
                ("DOB",        app.get("date_of_birth", "N/A")),
                ("PAN",        app.get("pan", "N/A")),
                ("Mobile",     app.get("mobile", "N/A")),
                ("Email",      app.get("email", "N/A")),
                ("Employment", app.get("employment_type", "N/A")),
                ("Loan Type",  app.get("loan_type", app.get("type", "N/A"))),
                ("Purpose",    app.get("loan_purpose", "N/A")),
                ("CIBIL",      app.get("cibil", "N/A")),
                ("Income/mo",  fmt_inr(app.get("monthly_income", 0))),
                ("Loan Amt",   fmt_inr(app.get("loan_amt", 0))),
                ("Tenure",     f"{app.get('tenure_months', 'N/A')} months"),
                ("Existing EMI", fmt_inr(app.get("existing_emi", 0))),
            ]
        else:
            title   = app.get("name", "N/A")
            details = [
                ("City",      app.get("city", "N/A")),
                ("Industry",  app.get("industry", "N/A")),
                ("PAN",       app.get("pan", "N/A")),
                ("GSTIN",     app.get("gstin", "N/A")),
                ("Mobile",    app.get("mobile", "N/A")),
                ("Email",     app.get("email", "N/A")),
                ("Promoter",  app.get("promoter_name", "N/A")),
                ("CIBIL",     app.get("cibil", "N/A")),
                ("Loan Type", app.get("loan_type", app.get("type", "N/A"))),
                ("Purpose",   app.get("loan_purpose", "N/A")),
                ("Turnover",  fmt_inr(app.get("turnover", 0))),
                ("Loan Amt",  fmt_inr(app.get("loan_amt", 0))),
                ("Vintage",   f"{app.get('vintage', 'N/A')} years"),
                ("Collateral", fmt_inr(app.get("collateral", 0))),
            ]

        side_panel_col.controls.append(
            ft.Text(title, size=16, weight="bold", color=ft.colors.CYAN_300)
        )
        side_panel_col.controls.append(ft.Divider(height=8))
        for lbl, val in details:
            side_panel_col.controls.append(kv_row(lbl, str(val)))
        side_panel_col.controls.append(
            ft.TextButton("✕  Close", on_click=lambda _: hide_side_panel())
        )

        side_container.visible = True
        page.update()

    def hide_side_panel():
        side_container.visible = False
        page.update()

    # ── Retail section ───────────────────────────────────────────────────────
    retail_dd_ref     = ft.Ref[ft.Dropdown]()
    retail_search_ref = ft.Ref[ft.TextField]()
    retail_progress   = ft.ProgressRing(visible=False, width=28, height=28)
    retail_status     = ft.Text("Ready", size=13, color=ft.colors.GREEN_300)
    selected_retail   = [None]

    def build_retail_options(query: str = "") -> list:
        q = query.lower()
        filtered = (
            [a for a in RETAIL_SAMPLES if
             q in a.get("city", "").lower() or
             q in a.get("name", "").lower() or
             q in a.get("employment_type", "").lower() or
             q in a.get("loan_type", a.get("type", "")).lower() or
             q in a.get("loan_purpose", "").lower()]
            if q else RETAIL_SAMPLES
        )
        return [
            ft.dropdown.Option(
                key=a["id"],
                text=f"{a['name']}  |  {a['city']}  |  {a.get('loan_type', a.get('type',''))}  |  "
                     f"{fmt_inr(a.get('loan_amt',0))}  |  CIBIL {a.get('cibil','')}"
            )
            for a in filtered[:500]
        ]

    def on_retail_search(e):
        retail_dd_ref.current.options = build_retail_options(retail_search_ref.current.value or "")
        page.update()

    def on_retail_select(e):
        if not retail_dd_ref.current.value:
            hide_side_panel()
            return
        app = next((a for a in RETAIL_SAMPLES if a["id"] == retail_dd_ref.current.value), None)
        if app:
            selected_retail[0] = app
            show_side_panel(app, is_retail=True)

    def process_retail(_e):
        app = selected_retail[0]
        if not app:
            page.show_snack_bar(ft.SnackBar(ft.Text("Please select a retail applicant first")))
            return
        active_mode[0] = "retail"
        retail_progress.visible = True
        retail_status.value     = "Processing…"
        page.update()
        try:
            result = _retail_pipeline.run(app)
            show_results(result, "retail")
            retail_status.value = f"Done – {result.get('decision','N/A')}"
        except Exception as ex:
            retail_status.value = f"Error: {ex}"
        finally:
            retail_progress.visible = False
            page.update()

    # ── SME section ──────────────────────────────────────────────────────────
    sme_dd_ref     = ft.Ref[ft.Dropdown]()
    sme_search_ref = ft.Ref[ft.TextField]()
    sme_progress   = ft.ProgressRing(visible=False, width=28, height=28)
    sme_status     = ft.Text("Ready", size=13, color=ft.colors.GREEN_300)
    selected_sme   = [None]

    def build_sme_options(query: str = "") -> list:
        q = query.lower()
        filtered = (
            [a for a in SME_SAMPLES if
             q in a.get("city", "").lower() or
             q in a.get("name", "").lower() or
             q in a.get("industry", "").lower() or
             q in a.get("loan_type", a.get("type", "")).lower() or
             q in a.get("loan_purpose", "").lower()]
            if q else SME_SAMPLES
        )
        return [
            ft.dropdown.Option(
                key=a["id"],
                text=f"{a['name']}  |  {a['city']}  |  {a.get('industry','')}  |  "
                     f"{a.get('loan_type', a.get('type',''))}  |  {fmt_inr(a.get('loan_amt',0))}"
            )
            for a in filtered[:500]
        ]

    def on_sme_search(e):
        sme_dd_ref.current.options = build_sme_options(sme_search_ref.current.value or "")
        page.update()

    def on_sme_select(e):
        if not sme_dd_ref.current.value:
            hide_side_panel()
            return
        app = next((a for a in SME_SAMPLES if a["id"] == sme_dd_ref.current.value), None)
        if app:
            selected_sme[0] = app
            show_side_panel(app, is_retail=False)

    def process_sme(_e):
        app = selected_sme[0]
        if not app:
            page.show_snack_bar(ft.SnackBar(ft.Text("Please select an SME applicant first")))
            return
        active_mode[0] = "sme"
        sme_progress.visible = True
        sme_status.value     = "Processing…"
        page.update()
        try:
            result = _sme_pipeline.run(app)
            show_results(result, "sme")
            sme_status.value = f"Done – {result.get('decision','N/A')}"
        except Exception as ex:
            sme_status.value = f"Error: {ex}"
        finally:
            sme_progress.visible = False
            page.update()

    # ── STT / translate ──────────────────────────────────────────────────────
    def translate_results(_e):
        text = "\n".join([
            c.controls[-1].value
            for c in results_col.controls
            if isinstance(c, ft.Row) and c.controls
        ])
        hindi = translate_to_hindi(text[:2000])
        results_col.controls.append(ft.Divider())
        results_col.controls.append(
            ft.Container(
                ft.Column([
                    ft.Text("हिंदी अनुवाद", weight="bold", color=ft.colors.YELLOW_200, size=16),
                    ft.Text(hindi, size=13, selectable=True),
                ]),
                bgcolor="#161b22",
                padding=14,
                border_radius=8,
            )
        )
        page.update()

    # ── Layout helpers ───────────────────────────────────────────────────────
    def section_title(text: str) -> ft.Text:
        return ft.Text(text, size=18, weight="bold", color=ft.colors.CYAN_300)

    def card(content: ft.Control) -> ft.Container:
        return ft.Container(
            content=content,
            bgcolor="#161b22",
            padding=20,
            border_radius=12,
            border=ft.border.all(1, "#30363d"),
        )

    # ── Applications tab ────────────────────────────────────────────────────
    retail_section = card(ft.Column([
        section_title("🏦  Retail Loan Applicants"),
        ft.Text(f"{len(RETAIL_SAMPLES):,} applicants loaded", size=12, color=ft.colors.GREY_500),
        ft.TextField(
            ref=retail_search_ref,
            label="🔍  Search by name / city / loan type / purpose",
            on_change=on_retail_search,
            border_color="#30363d",
            focused_border_color=ft.colors.CYAN_400,
        ),
        ft.Dropdown(
            ref=retail_dd_ref,
            label="Select Retail Applicant",
            options=build_retail_options(),
            on_change=on_retail_select,
            bgcolor="#0d1117",
        ),
        ft.Row([
            ft.ElevatedButton(
                "▶  Process Retail",
                on_click=process_retail,
                icon=ft.icons.PLAY_CIRCLE_FILLED,
                bgcolor=ft.colors.CYAN_700,
                color=ft.colors.WHITE,
                height=46,
            ),
            retail_progress,
            retail_status,
        ], spacing=14),
    ], spacing=14))

    sme_section = card(ft.Column([
        section_title("🏭  SME / Corporate Trade Finance Applicants"),
        ft.Text(f"{len(SME_SAMPLES):,} applicants loaded", size=12, color=ft.colors.GREY_500),
        ft.TextField(
            ref=sme_search_ref,
            label="🔍  Search by name / city / industry / loan type",
            on_change=on_sme_search,
            border_color="#30363d",
            focused_border_color=ft.colors.AMBER_400,
        ),
        ft.Dropdown(
            ref=sme_dd_ref,
            label="Select SME Applicant",
            options=build_sme_options(),
            on_change=on_sme_select,
            bgcolor="#0d1117",
        ),
        ft.Row([
            ft.ElevatedButton(
                "▶  Process SME",
                on_click=process_sme,
                icon=ft.icons.PLAY_CIRCLE_FILLED,
                bgcolor=ft.colors.AMBER_700,
                color=ft.colors.WHITE,
                height=46,
            ),
            sme_progress,
            sme_status,
        ], spacing=14),
    ], spacing=14))

    left_col = ft.Column(
        [retail_section, sme_section],
        spacing=20,
        expand=2,
        scroll=ft.ScrollMode.AUTO,
    )

    applications_tab = ft.Row(
        [left_col, side_container],
        spacing=16,
        expand=True,
        vertical_alignment=ft.CrossAxisAlignment.START,
    )

    # ── Results tab ─────────────────────────────────────────────────────────
    results_tab = ft.Column([
        ft.Container(
            content=results_col,
            expand=True,
            bgcolor="#161b22",
            padding=20,
            border_radius=12,
            border=ft.border.all(1, "#30363d"),
        ),
        ft.Row([
            ft.ElevatedButton(
                "🌐  Translate to हिंदी",
                on_click=translate_results,
                icon=ft.icons.TRANSLATE,
                bgcolor="#21262d",
            ),
            ft.ElevatedButton(
                "🗑  Clear",
                on_click=lambda _: [results_col.controls.clear(), page.update()],
                bgcolor="#21262d",
            ),
        ], spacing=12),
    ], expand=True, spacing=12)

    # ── Tabs ────────────────────────────────────────────────────────────────
    tabs_ctrl = ft.Tabs(
        selected_index=0,
        animation_duration=200,
        tabs=[
            ft.Tab(text="  Applications  ", content=applications_tab),
            ft.Tab(text="  Results  ",      content=results_tab),
        ],
        expand=True,
    )

    # ── Header ──────────────────────────────────────────────────────────────
    header = ft.Container(
        ft.Row([
            ft.Text("  Loan Processing Demo", size=26, weight="bold", color=ft.colors.CYAN_300),
            ft.Text("Retail + SME | AI-Powered Multi-Agent Pipeline", size=13, color=ft.colors.GREY_500),
        ], alignment=ft.MainAxisAlignment.SPACE_BETWEEN),
        bgcolor="#161b22",
        padding=ft.padding.symmetric(horizontal=28, vertical=14),
        border=ft.border.only(bottom=ft.border.BorderSide(1, "#30363d")),
    )

    page.add(
        ft.Column([
            header,
            ft.Container(content=tabs_ctrl, expand=True, padding=20),
        ], spacing=0, expand=True)
    )
    page.update()


ft.app(target=main)
