# retail_pipeline.py
"""
Complete Retail Loan Processing Pipeline
10 agents: Intake → KYC → Income/FOIR → Credit Bureau → Property/LTV →
           Decisioning → Sanction → Documentation → Disbursement → Monitoring

Data source: retail_applicants.json / retail_applicants.csv
             (generated by synthetic_data_generator.py)
"""
import time
import math
import random
from typing import Dict, Any


class RetailIntakeAgent:
    """Agent 1 – Digital Intake & Lead Scoring"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.3)
        cibil        = data.get("cibil_score", data.get("cibil", 650))
        age          = data.get("age", 35)
        tenure_years = data.get("tenure_months", 36) / 12.0
        pre_approved = cibil >= 700 and 21 <= age <= 70 and (age + tenure_years) <= 70
        return {
            "pre_approved":  pre_approved,
            "lead_score":    round(70 + (cibil - 650) * 0.12, 1) if pre_approved else 48.0,
            "journey_type":  "express_digital" if pre_approved else "standard",
            "status":        "intake_complete",
        }


class RetailKycAgent:
    """Agent 2 – KYC & Identity Verification"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.4)
        success = random.random() < 0.92
        return {
            "kyc_status":       "complete" if success else "failed",
            "identity_verified": success,
            "liveness_score":   round(random.uniform(92, 99), 1) if success else 45.2,
            "kyc_risk_level":   "low" if success else "high",
            "status":           "kyc_complete" if success else "kyc_failed",
        }


class RetailIncomeAgent:
    """Agent 3 – Income & Creditworthiness (FOIR calculation)"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.4)
        gross_income  = data.get("monthly_income", 50000)
        net_income    = round(gross_income * 0.85, 0)
        existing_emi  = data.get("existing_emi", 0)
        loan_amount   = data.get("loan_amount_requested", data.get("loan_amt", 500000))
        tenure        = data.get("tenure_months", 36)
        rate          = data.get("indicative_rate", 12.5)

        r = rate / 12 / 100
        if r == 0:
            proposed_emi = loan_amount / tenure
        else:
            proposed_emi = loan_amount * r * math.pow(1 + r, tenure) / (math.pow(1 + r, tenure) - 1)

        total_obligations = existing_emi + proposed_emi
        foir_post = (total_obligations / net_income) * 100 if net_income > 0 else 999

        max_foir = 50
        if net_income < 25000:
            max_foir = 45
        elif net_income >= 100000:
            max_foir = 60

        foir_pre = (existing_emi / net_income) * 100 if net_income > 0 else 0
        eligible  = foir_post <= max_foir + 5

        return {
            "gross_monthly_income":   gross_income,
            "net_monthly_income":     net_income,
            "existing_emi":           existing_emi,
            "proposed_emi":           round(proposed_emi, 0),
            "total_obligations":      round(total_obligations, 0),
            "foir_pre_loan":          round(foir_pre, 2),
            "foir_post_loan":         round(foir_post, 2),
            "max_allowed_foir":       max_foir,
            "foir_status":            "PASS" if eligible else "FAIL",
            "eligible_loan_amount":   round(min(loan_amount, net_income * 0.5 * 12), -3) if eligible else 0,
            "repayment_capacity_monthly": round(net_income * 0.55, 0),
            "status":                 "income_analyzed",
        }


class RetailCreditBureauAgent:
    """Agent 4 – Credit Bureau & Fraud Detection"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.3)
        cibil       = data.get("cibil_score", data.get("cibil", 650))
        fraud_score = round(10 + (900 - cibil) * 0.1, 1)
        grade = (
            "A" if cibil >= 750 else
            "B" if cibil >= 700 else
            "C" if cibil >= 650 else "D"
        )
        return {
            "cibil_score":      cibil,
            "bureau_risk_grade": grade,
            "fraud_score":      fraud_score,
            "status":           "bureau_complete",
        }


class RetailPropertyAgent:
    """Agent 5 – Property Appraisal (Home Loan only)"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.5)
        loan_type = data.get("loan_type", data.get("type", ""))
        if loan_type != "home_loan":
            return {"status": "not_applicable", "ltv_ratio": 0, "max_allowed_ltv": 80}

        loan_amount  = data.get("loan_amount_requested", data.get("loan_amt", 0))
        market_value = loan_amount * random.uniform(1.25, 1.6)
        ltv          = round((loan_amount / market_value) * 100, 1)
        prop_type    = data.get("property_type", "ready_to_move") or "ready_to_move"
        max_ltv      = 80 if "ready_to_move" in prop_type else 75

        return {
            "market_value":    round(market_value, -3),
            "ltv_ratio":       ltv,
            "max_allowed_ltv": max_ltv,
            "title_clear":     random.random() < 0.95,
            "legal_risk_rating": "green" if ltv <= max_ltv else "amber",
            "status":          "property_appraised",
        }


class RetailDecisioningAgent:
    """Agent 6 – Credit Decisioning & Risk Pricing"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.3)
        hard_rejects = []
        cibil      = data.get("cibil_score", data.get("cibil", 0))
        foir_post  = data.get("foir_post_loan", 0)
        fraud      = data.get("fraud_score", 0)
        ltv        = data.get("ltv_ratio", 0)
        max_ltv    = data.get("max_allowed_ltv", 80)

        if cibil < 650:           hard_rejects.append("CIBIL < 650")
        if foir_post > 65:        hard_rejects.append("FOIR > 65%")
        if fraud > 80:            hard_rejects.append("High fraud score")
        if ltv > max_ltv + 5:     hard_rejects.append("LTV exceeds limit")
        if not data.get("identity_verified", True):
            hard_rejects.append("KYC failed")

        if hard_rejects:
            return {
                "decision":   "REJECT",
                "rationale":  hard_rejects,
                "final_score": 40,
                "status":     "rejected",
            }

        score = (
            data.get("lead_score", 70) * 0.25 +
            (100 - foir_post) * 0.25 +
            (cibil / 9) * 0.30 +
            (100 - ltv) * 0.20
        )
        score = round(min(98, max(25, score)), 1)

        if score >= 80:   decision = "STP_APPROVE"
        elif score >= 65: decision = "APPROVE_WITH_CONDITIONS"
        elif score >= 50: decision = "MANUAL_REVIEW"
        else:             decision = "REJECT"

        loan_amount  = data.get("loan_amount_requested", data.get("loan_amt", 0))
        eligible_amt = data.get("eligible_loan_amount", loan_amount)

        return {
            "final_score":         score,
            "decision":            decision,
            "approved_amount":     eligible_amt if decision != "REJECT" else 0,
            "interest_rate":       round(10.5 + (90 - score) * 0.08, 2) if decision != "REJECT" else None,
            "decision_rationale":  (
                ["Strong CIBIL", "FOIR acceptable", "Good LTV"]
                if decision != "REJECT" else hard_rejects
            ),
            "status": "decision_complete",
        }


class RetailSanctionAgent:
    """Agent 7 – Sanction & Offer Letter"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.3)
        if data.get("decision") in ("REJECT", None):
            return {"status": "not_applicable"}
        return {
            "offer_generated": True,
            "sanction_status": "ISSUED",
            "status":          "sanctioned",
        }


class RetailDocumentationAgent:
    """Agent 8 – Documentation & NACH Registration"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.4)
        return {
            "docs_esigned":          True,
            "nach_umrn":             f"NACH{random.randint(10000000, 99999999)}",
            "nach_registered":       True,
            "documentation_complete": True,
            "status":                "docs_complete",
        }


class RetailDisbursementAgent:
    """Agent 9 – Disbursement"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.4)
        if not data.get("documentation_complete"):
            return {"status": "pending_docs"}
        amount = data.get("approved_amount", 0)
        return {
            "disbursed_amount":   amount,
            "disbursement_mode":  "IMPS" if amount < 200000 else "NEFT",
            "loan_account_number": f"RL{random.randint(10000000, 99999999)}",
            "status":             "disbursed",
        }


class RetailMonitoringAgent:
    """Agent 10 – Collections & Retention"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.3)
        return {
            "dpd_current":    random.randint(0, 8),
            "npa_risk_score": round(random.uniform(12, 38), 1),
            "status":         "monitoring_active",
        }


# ─────────────────────────────────────────────────────────────────────────────
# Orchestrator
# ─────────────────────────────────────────────────────────────────────────────

class RetailPipeline:
    """Orchestrates the full Retail loan pipeline across 10 agents."""

    STAGE_ORDER = [
        "intake", "kyc", "income", "credit",
        "property", "decision", "sanction",
        "documentation", "disbursement", "monitoring",
    ]

    def __init__(self):
        self.agents = {
            "intake":        RetailIntakeAgent(),
            "kyc":           RetailKycAgent(),
            "income":        RetailIncomeAgent(),
            "credit":        RetailCreditBureauAgent(),
            "property":      RetailPropertyAgent(),
            "decision":      RetailDecisioningAgent(),
            "sanction":      RetailSanctionAgent(),
            "documentation": RetailDocumentationAgent(),
            "disbursement":  RetailDisbursementAgent(),
            "monitoring":    RetailMonitoringAgent(),
        }

    def run(self, application: Dict) -> Dict:
        state = application.copy()
        # Normalise key aliases from JSON
        if "cibil" in state and "cibil_score" not in state:
            state["cibil_score"] = state["cibil"]
        if "loan_amt" in state and "loan_amount_requested" not in state:
            state["loan_amount_requested"] = state["loan_amt"]
        if "type" in state and "loan_type" not in state:
            state["loan_type"] = state["type"]

        state["logs"]          = []
        state["stage_history"] = []

        for stage_name in self.STAGE_ORDER:
            agent  = self.agents[stage_name]
            result = agent.process(state)
            state.update(result)
            state["logs"].append(
                f"[{stage_name.upper():15s}] {result.get('status', 'processed')}"
            )
            state["stage_history"].append(stage_name)
            if result.get("decision") == "REJECT":
                break

        return state


# ─────────────────────────────────────────────────────────────────────────────
# Standalone test
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import json

    # Load from synthetic data
    with open("retail_applicants.json", "r", encoding="utf-8") as f:
        samples = json.load(f)

    sample_app = samples[0]
    print(f"Processing: {sample_app['name']} | {sample_app['city']} | {sample_app['loan_type']}")

    pipeline = RetailPipeline()
    result   = pipeline.run(sample_app)

    print(f"\nDecision      : {result.get('decision')}")
    print(f"FOIR post-loan: {result.get('foir_post_loan')}%")
    print(f"Approved Amt  : ₹{result.get('approved_amount', 0):,.0f}")
    print(f"NACH UMRN     : {result.get('nach_umrn', 'N/A')}")
    print("\nStage Logs:")
    for log in result.get("logs", []):
        print(f"  {log}")
