# sme_pipeline.py
"""
Complete SME / Corporate Trade Finance Loan Processing Pipeline
10 agents: Intake → KYC → Financial Analysis → Credit Bureau → Collateral →
           Underwriting → Sanction → Documentation → Disbursement → Monitoring

Data source: sme_applicants.json / sme_applicants.csv
             (generated by synthetic_data_generator.py)
"""
import time
import math
import random
from typing import Dict, Any


class SMEIntakeAgent:
    """Agent 1 – Lead Intake & Application Validation"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.3)
        vintage  = data.get("business_vintage_years", data.get("vintage", 0))
        turnover = data.get("annual_turnover", data.get("turnover", 0))
        loan_amt = data.get("loan_amount_requested", data.get("loan_amt", 0))

        valid            = vintage >= 3 and turnover >= 1_500_000
        turnover_ratio_ok = loan_amt <= turnover * 2

        return {
            "intake_valid":       valid,
            "turnover_ratio_ok":  turnover_ratio_ok,
            "lead_score":         round(60 + vintage * 4 + (turnover / 1_000_000) * 0.8, 1) if valid else 30.0,
            "status":             "intake_complete" if valid else "rejected - vintage/turnover",
        }


class SMEKycAgent:
    """Agent 2 – KYC & Document Collection"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.4)
        success = random.random() < 0.90
        return {
            "kyc_status":       "complete" if success else "incomplete",
            "face_match_score": round(random.uniform(88, 99), 1) if success else 62.5,
            "kyc_risk_flags":   [] if success else ["PAN-Aadhaar mismatch"],
            "status":           "kyc_complete" if success else "kyc_pending",
        }


class SMEFinancialAnalysisAgent:
    """Agent 3 – Financial Analysis: DSCR, ratios, GST & bank mock"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.5)
        turnover     = data.get("annual_turnover", data.get("turnover", 20_000_000))
        net_profit   = turnover * random.uniform(0.08, 0.18)
        depreciation = turnover * 0.07
        loan_amt     = data.get("loan_amount_requested", data.get("loan_amt", 0))
        debt_service = loan_amt * 0.14  # mock annual debt service

        dscr          = round((net_profit + depreciation) / max(debt_service, 1), 2)
        current_ratio = round(random.uniform(1.05, 2.9), 2)
        debt_equity   = round(random.uniform(1.2, 4.0), 2)
        gross_margin  = round(random.uniform(12, 28), 1)

        health_score = round(
            30 +
            min(dscr * 30, 40) +
            (current_ratio - 1) * 15 +
            (28 - abs(debt_equity - 2.0)) * 5,
            1,
        )
        health_score = min(98, max(25, health_score))

        return {
            "dscr":                  dscr,
            "current_ratio":         current_ratio,
            "debt_to_equity":        debt_equity,
            "gross_profit_margin":   gross_margin,
            "financial_health_score": health_score,
            "status":                "financial_analysis_complete",
        }


class SMECreditBureauAgent:
    """Agent 4 – Credit Bureau & External Data"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.3)
        cibil = data.get("promoter_cibil_score", data.get("cibil", 680))
        grade = (
            "A" if cibil >= 750 else
            "B" if cibil >= 700 else
            "C" if cibil >= 650 else "D"
        )
        return {
            "promoter_cibil_score": cibil,
            "bureau_risk_grade":    grade,
            "status":               "bureau_complete",
        }


class SMECollateralAgent:
    """Agent 5 – Collateral Verification & LTV"""

    LTV_MATRIX = {
        "residential_property": 75,
        "commercial_property":  65,
        "industrial_property":  60,
        "plant_machinery":      50,
        "book_debts":           75,
        "stock":                65,
        "term_loan":            70,
        "working_capital":      65,
        "equipment_finance":    55,
        "invoice_discounting":  80,
        "project_finance":      60,
    }

    def process(self, data: Dict) -> Dict:
        time.sleep(0.5)
        loan_type        = data.get("loan_type", data.get("type", "term_loan"))
        requested        = data.get("loan_amount_requested", data.get("loan_amt", 0))
        collateral_value = data.get("collateral_value", data.get("collateral", 0))

        if collateral_value == 0:
            collateral_value = requested * random.uniform(1.3, 1.8)

        ltv     = round((requested / max(collateral_value, 1)) * 100, 1)
        max_ltv = self.LTV_MATRIX.get(loan_type, 70)

        return {
            "collateral_value":  round(collateral_value, -3),
            "ltv_ratio":         ltv,
            "max_allowed_ltv":   max_ltv,
            "title_clear":       random.random() < 0.93,
            "collateral_status": "PASS" if ltv <= max_ltv + 5 else "REVIEW / FAIL",
            "status":            "collateral_verified",
        }


class SMEUnderwritingAgent:
    """Agent 6 – Risk Scoring & Underwriting (Decision Matrix)"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.4)
        vintage = data.get("business_vintage_years", data.get("vintage", 0))
        cibil   = data.get("promoter_cibil_score", data.get("cibil", 650))
        dscr    = data.get("dscr", 1.0)
        health  = data.get("financial_health_score", 60)
        ltv     = data.get("ltv_ratio", 70)

        vintage_score = min(vintage * 2, 20)
        cibil_score   = min(max((cibil - 600) / 3, 0), 25)
        dscr_score    = min(max(dscr * 15, 0), 20)
        health_score  = health * 0.3
        ltv_penalty   = max(0, (ltv - 65) * 0.5)

        total = round(vintage_score + cibil_score + dscr_score + health_score - ltv_penalty, 1)
        total = min(98, max(20, total))

        if total >= 80:   decision, tier = "AUTO_APPROVE",               "TIER_1"
        elif total >= 65: decision, tier = "APPROVE_WITH_CONDITIONS",     "TIER_2"
        elif total >= 50: decision, tier = "REFER_TO_CREDIT_COMMITTEE",   "TIER_3"
        else:             decision, tier = "REJECT",                      "REJECT"

        loan_amt = data.get("loan_amount_requested", data.get("loan_amt", 0))

        return {
            "total_score":        total,
            "risk_grade": (
                "AAA" if total >= 85 else
                "AA"  if total >= 75 else
                "A"   if total >= 65 else "BBB"
            ),
            "decision":           decision,
            "approved_loan_amount": round(loan_amt * 0.9, -3) if decision != "REJECT" else 0,
            "interest_rate":      (
                11.75 if total >= 80 else
                13.50 if total >= 65 else 15.75
            ),
            "status":             "underwriting_complete",
        }


class SMESanctionAgent:
    """Agent 7 – Sanction & Approval"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.3)
        if data.get("decision") == "REJECT":
            return {"status": "not_applicable"}

        conditions = []
        if data.get("ltv_ratio", 100) > data.get("max_allowed_ltv", 70):
            conditions.append("Additional collateral / higher margin required")
        if data.get("dscr", 1.5) < 1.25:
            conditions.append("Step-up repayment / moratorium suggested")

        return {
            "sanctioned_amount":    data.get("approved_loan_amount", 0),
            "final_interest_rate":  data.get("interest_rate", 13.0),
            "sanction_conditions":  conditions,
            "sanction_validity_days": 90,
            "status":               "sanction_issued",
        }


class SMEDocumentationAgent:
    """Agent 8 – Documentation & Legal (NACH mock)"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.4)
        return {
            "docs_esigned":          True,
            "nach_umrn":             f"NACH{random.randint(100_000_000, 999_999_999)}",
            "nach_registered":       True,
            "documentation_complete": True,
            "status":                "documentation_complete",
        }


class SMEDisbursementAgent:
    """Agent 9 – Disbursement"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.4)
        if not data.get("documentation_complete", False):
            return {"status": "pending_docs"}
        amount = data.get("sanctioned_amount", 0)
        return {
            "disbursed_amount":     amount,
            "disbursement_mode":    "RTGS" if amount >= 200_000 else "NEFT",
            "loan_account_number":  f"SME{random.randint(10_000_000, 99_999_999)}",
            "disbursement_status":  "SUCCESS",
            "status":               "disbursed",
        }


class SMEMonitoringAgent:
    """Agent 10 – Monitoring & NPA Management"""

    def process(self, data: Dict) -> Dict:
        time.sleep(0.3)
        dpd = random.randint(0, 45)
        return {
            "dpd_current":     dpd,
            "npa_risk_score":  round(random.uniform(8, 45), 1),
            "loan_health_score": round(100 - dpd * 1.8, 1),
            "status":          "monitoring_active",
        }


# ─────────────────────────────────────────────────────────────────────────────
# Orchestrator
# ─────────────────────────────────────────────────────────────────────────────

class SMEPipeline:
    """Orchestrates the full SME loan pipeline across 10 agents."""

    STAGE_ORDER = [
        "intake", "kyc", "financial", "credit",
        "collateral", "underwriting", "sanction",
        "documentation", "disbursement", "monitoring",
    ]

    def __init__(self):
        self.agents = {
            "intake":        SMEIntakeAgent(),
            "kyc":           SMEKycAgent(),
            "financial":     SMEFinancialAnalysisAgent(),
            "credit":        SMECreditBureauAgent(),
            "collateral":    SMECollateralAgent(),
            "underwriting":  SMEUnderwritingAgent(),
            "sanction":      SMESanctionAgent(),
            "documentation": SMEDocumentationAgent(),
            "disbursement":  SMEDisbursementAgent(),
            "monitoring":    SMEMonitoringAgent(),
        }

    def run(self, application: Dict) -> Dict:
        state = application.copy()
        # Normalise key aliases from JSON
        if "turnover" in state and "annual_turnover" not in state:
            state["annual_turnover"] = state["turnover"]
        if "vintage" in state and "business_vintage_years" not in state:
            state["business_vintage_years"] = state["vintage"]
        if "loan_amt" in state and "loan_amount_requested" not in state:
            state["loan_amount_requested"] = state["loan_amt"]
        if "type" in state and "loan_type" not in state:
            state["loan_type"] = state["type"]
        if "cibil" in state and "promoter_cibil_score" not in state:
            state["promoter_cibil_score"] = state["cibil"]
        if "collateral" in state and "collateral_value" not in state:
            state["collateral_value"] = state["collateral"]

        state["logs"]          = []
        state["stage_history"] = []

        for stage_name in self.STAGE_ORDER:
            agent  = self.agents[stage_name]
            result = agent.process(state)
            state.update(result)
            state["logs"].append(
                f"[{stage_name.upper():15s}] "
                f"{result.get('status', result.get('disbursement_status', 'processed'))}"
            )
            state["stage_history"].append(stage_name)
            if (result.get("decision") == "REJECT" or
                    result.get("intake_valid") is False):
                break

        return state


# ─────────────────────────────────────────────────────────────────────────────
# Standalone test
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import json

    with open("sme_applicants.json", "r", encoding="utf-8") as f:
        samples = json.load(f)

    sample = samples[1]
    print(f"Processing: {sample['name']} | {sample['city']} | {sample['loan_type']}")

    pipeline = SMEPipeline()
    result   = pipeline.run(sample)

    print(f"\nDecision      : {result.get('decision', 'N/A')}")
    print(f"Total Score   : {result.get('total_score', 'N/A')}")
    print(f"DSCR          : {result.get('dscr', 'N/A')}")
    print(f"LTV           : {result.get('ltv_ratio', 'N/A')}%")
    print(f"NACH UMRN     : {result.get('nach_umrn', 'N/A')}")
    print(f"Sanctioned Amt: ₹{result.get('sanctioned_amount', 0):,.0f}")
    print("\nStage Logs:")
    for log in result.get("logs", []):
        print(f"  {log}")
